### ISSUE TITLE
[FR]希望可以添加 HOOK_AFTER_JUMP 选项

### ISSUE THREAD

**Issue by aQuaYi** [skywind3000/z.lua#103]
[enhancd](https://github.com/b4b4r07/enhancd#configurations) 有这样一个选项

>ENHANCD_HOOK_AFTER_CD
>Default is empty. You can run any commands after changing directory with enhancd (e.g. ls: like cd && ls).

个人觉得蛮好用的，我设置成了 `ls -a` 进入新目录后，会自动显示目录的内容。毕竟，ls 接在 cd 后面的几率还是蛮高的。

**Comment by skywind3000** [comment]
你可以修改 `$_ZL_CD` 成你想要的指令，比如 cd 加一个 ls

**Comment by aQuaYi** [comment]
@skywind3000 
export _ZL_CD='cd && exa --classify -a' ?

**Comment by skywind3000** [comment]
它调用的方式是 $_ZL_CD  "newpath" 你这样接收不到命令参数，你要提供一个函数

```bash
function my_cd() { cd "$1" && exa --classify -a; }
export _ZL_CD=my_cd
```

**Comment by aQuaYi** [comment]
@skywind3000 谢谢
