### ISSUE TITLE
Feature request: support postcommand hook

### ISSUE THREAD

**Issue by trobjo** [skywind3000/z.lua#107]
First of all, thank you for a really nice plugin!

I have experimented with the `$_ZL_CD` variable to no avail. I would like if z.lua could support a post command hook, so that it automatically runs a command after changing dir.

In my .zshrc I have `alias cd='clear; cd $@; ls'`

That way, I am always told what is in the dir I am switching to.

**Comment by skywind3000** [comment]
try this:

```bash
my_cd() { clear; builtin cd "$@"; ls; }
_ZL_CD=my_cd
```

**Comment by trobjo** [comment]
Works perfectly, thanks!
