### ISSUE TITLE
Anyway to be managed by plug manager?

### ISSUE THREAD

**Issue by meijieru** [skywind3000/z.lua#11]
Thanks for the excellent work.
Could we install this software through antigen?

**Comment by skywind3000** [comment]
Where can I find the documentation about antigen integration ??

**Comment by skywind3000** [comment]
done, added a "omz.plugin.zsh"

**Comment by meijieru** [comment]
Thx!

**Comment by jdhao** [comment]
I have verified that this plugin can be installed with antigen using the following setting in `.zshrc`:

```
antigen bundle skywind3000/z.lua
```
