### ISSUE TITLE
Command made no reponse

### ISSUE THREAD

**Issue by Syusyuly** [skywind3000/z.lua#116]
使用环境为 WSL2 Ubuntu 20.04 LTS + Zsh + Oh-My-Zsh，使用 sudo apt install lua5.3 安装 lua 环境

```
plugins=(git
        zsh-autosuggestions
        zsh-syntax-highlighting
        z.lua
)
```
![image](https://user-images.githubusercontent.com/29004625/91280595-8b48ee00-e7b9-11ea-9af5-90d3060c2f6e.png)

由下图可见 z .. 回到上一级目录和 z 打开非当前目录下的目录的功能均已失效
![image](https://user-images.githubusercontent.com/29004625/91280738-c5b28b00-e7b9-11ea-995f-787ca2a8dad5.png)

**Comment by Syusyuly** [comment]
此外 Lua CPU 占用率可达 100%
![image](https://user-images.githubusercontent.com/29004625/91282159-8dac4780-e7bb-11ea-94e6-37e92dc2ca45.png)

**Comment by skywind3000** [comment]
新版本 wsl 的问题：
https://github.com/microsoft/WSL/issues/5505

解决方法：

    sudo  apt-get install lua-filesystem

这样 z.lua 会使用 lua-filesystem 模块中的 api 判断目录/文件存不存在。

**Comment by skywind3000** [comment]
再，你这是 wsl1 不是 wsl2，wsl2 的内部进程在 windows 进程管理器里是看不到的。

**Comment by Syusyuly** [comment]
感谢解答,实测可行
所使用的 wsl 是 Windows Store 安装的，应该是 wsl2 吧？

**Comment by skywind3000** [comment]
不是，你自己 cat /proc/version 就看出来了，不是 linux 内核。

**Comment by Syusyuly** [comment]
您是对的，在 PowerShell 运行 `wsl --list --verbose` 指令显示的 Version 是一代，看来是我忘记运行 `wsl --set-default-version 2` 指令，受教了
