### ISSUE TITLE
Not work in bash

### ISSUE THREAD

**Issue by adoyle-h** [skywind3000/z.lua#12]
```
# .bashrc
if [[ ! -f $DOTFILE_DIR/pkgs/z.lua/z.lua ]]; then
  return 0
fi

_ZL_CMD=z
_ZL_DATA=$HOME/.z_lua
_ZL_NO_PROMPT_COMMAND=true
# _ZL_EXCLUDE_DIRS=(.git)
# _ZL_CD=cd
_ZL_MATCH_MODE=1

eval "$(lua "$DOTFILE_DIR"/pkgs/z.lua/z.lua --init bash)"

alias zc='z -c'      # restrict matches to subdirs of $PWD
alias zz='z -i'      # cd with interactive selection
alias zf='cd "$(z -l -s | fzf --reverse --height 35%)"'
```

![image](https://user-images.githubusercontent.com/1998490/52100268-cf8dff80-2611-11e9-933f-2941015793ec.png)

And I find the directory which `_ZL_DATA` points to is empty.

---
bash version: GNU bash，version 4.4.12(1)-release (x86_64-apple-darwin15.6.0)
lua version: 5.3.4

**Comment by skywind3000** [comment]
export _ZL_CMD=z
export _ZL_DATA=$HOME/.z_lua
export _ZL_MATCH_MODE=1

**Comment by adoyle-h** [comment]
@skywind3000 

```
# .bashrc
eval "$(lua "$DOTFILE_DIR"/pkgs/z.lua/z.lua --init bash)"
```

I change the `.bashrc` and use the default configuration. But it still not works.

**Comment by skywind3000** [comment]
try:

    eval "$(lua /your/actual/path/pkgs/z.lua/z.lua --init bash)"

or

    eval "$(lua $DOTFILE_DIR/pkgs/z.lua/z.lua --init bash)"

**Comment by adoyle-h** [comment]
It is my fault. _ZL_DATA file has not recorded any paths, because I have not `cd` to any directories before invoking `z`. So that is the reason why `z` command not works.
Thanks for your help.
