### ISSUE TITLE
Interactive mode (`-I` / `-i`) without arguments

### ISSUE THREAD

**Issue by kankaristo** [skywind3000/z.lua#122]
I started using z.lua a few days ago, and it's awesome, thanks for writing it!

One thing that I would like would be a "fully interactive" mode.
Or in other words, for `z -i` and `z -I` to open an interactive prompt even without giving a path fragment.

Currently, `z`, `z -i`, or `z -I` (with no other arguments) all do the same thing.

-----

What I'm after is that running something `z -I` would give the full list of paths inside z.lua (like it currently does), and pass those to fzf to filter them.
So, similar to running something like `z -I a`, but for all entries inside z.lua, not just the ones that contain "a".

Something like this might make less sense for `z -i`, since it doesn't interactively filter the list while typing.

-----

I'm getting pretty much what I want with `cd "$(z | fzf | tr -s " " | cut -d" " -f2-)"` (could be improved, but works passably).

I could make an alias/function for the above, but I think it would make sense for `z -I` to enter an interactive mode, even if you don't give it a path fragment.

**Comment by skywind3000** [comment]
you may try:

    alias zd='z -I .'

and use `zd` for that purpose, `.` represents `any character` in lua's regexp

**Comment by kankaristo** [comment]
Ah, okay, that does exactly what I want. :smile:

Any thoughts on having `z -I` do this by default? Doesn't make sense to me that the `-I` and `-i` are effectively ignored, if you don't give any input (they do the same as just running `z` without arguments).

Using `-I`/`-i` without other parameters could also show a warning/message that using `-I`/`-i` requires input (although I have `z` aliased to `_zlua -I`, so that would break running just `z` for me, and possibly others).

Either way, I'll close the issue, since the feature that I wanted already exists. :stuck_out_tongue:

**Comment by skywind3000** [comment]
using `z -i` for listing is to keep corresponding user experience with `z.sh` 's `z -i`.

**Comment by chrisant996** [comment]
> using `z -i` for listing is to keep corresponding user experience with `z.sh` 's `z -i`.

@skywind3000 [z.sh](https://github.com/rupa/z) doesn't seem to have a `-i` flag.  Why does z.lua need to act like z.sh for a feature that z.sh doesn't have?

I have a small patch [here](https://github.com/chrisant996/z.lua/commit/c524e2885151c7dd6bec660f7b6126f3f8a53d30) that makes `z -i` and `z -I` be interactive.
I can share it as a pull request -- let me know if you're interested.

**Comment by skywind3000** [comment]
@chrisant996 Can't remember where it comes from, maybe from another z.sh port like in powershell.

anyway, doesn't matter now,

Yes please create a PR for that.
