### ISSUE TITLE
_zlua_precmd:1: nice(5) failed: invalid argument

### ISSUE THREAD

**Issue by adworacz** [skywind3000/z.lua#128]
version: 1.8.11

For some reason I stared receiving this whenever I open a new terminal or run a command.

*However*, when I run a tmux session, the error does *not* occur for any windows/panes.

I did some very basic debugging, and it looks like the _zlua --add command is failing?
```
foo % which _zlua_precmd
_zlua_precmd () {
	(
		_zlua --add "${PWD:a}" &
	)
}
_zlua_precmd:1: nice(5) failed: invalid argument


foo % _zlua --add "${PWD:a}" &
[1] 9123
[1]  + exit 1     _zlua --add "${PWD:a}"
_zlua_precmd:1: nice(5) failed: invalid argument
```

**Comment by skywind3000** [comment]
What system are you using ? 

There is no `nice` call in z.lua, what cause the `nice` calling ??

Anything special in your `.zshrc` that will setup an auto `nice` invocation ??

**Comment by skywind3000** [comment]
try this:

    unsetopt BG_NICE

in the end of your `.zshrc`

**Comment by adworacz** [comment]
Hmmm, that seems to have fixed it, the `unsetopt BG_NICE` that is.

I'm running on Ubuntu 18.04 in this case. A very similar setup on Manjaro doesn't have these issues.

I'm running Ananicy, which adjusts niceness of certain programs. It doesn't touch zsh at all, but I'm wondering if some other transitive dependency is trickling the niceness down.

Thanks for the fix! I consider this resolved.
