### ISSUE TITLE
z优先跳转到权重最高的目录而不是名字匹配的目录

### ISSUE THREAD

**Issue by longcp** [skywind3000/z.lua#129]
例如：/aaa/bbb/ccc
ccc权重最高，当我执行z bbb，跳到的竟然是ccc，而不是bbb，这结果有点出人意料。因为我还需要z -b bbb才能去到我想去的bbb。
有没方法可以优先跳转到名字匹配的路径，再跳转权重最高的路径。
![Snipaste_2021-02-08_10-09-46](https://user-images.githubusercontent.com/10282683/107168156-cc465f00-69f5-11eb-9bd3-943c3180f4c0.png)

**Comment by longcp** [comment]
![image](https://user-images.githubusercontent.com/10282683/107169006-ce112200-69f7-11eb-95b2-b622b151e7e3.png)
autojump则不会

**Comment by skywind3000** [comment]
因为 ccc 里任然包含你的关键词 bbb 啊，你上面的路径不都是含有 `dev` 字样的么？

如果你只想匹配路径名的最后一部分，你可以用 `z dev$` 显示指明这是最后一部分，

或者可以用增强路径匹配：

https://github.com/skywind3000/z.lua/blob/master/README.cn.md#%E5%A2%9E%E5%BC%BA%E5%8C%B9%E9%85%8D%E7%AE%97%E6%B3%95

**Comment by longcp** [comment]
感谢！
z dev$或增加模式都能满足我需求，感谢！
