### ISSUE TITLE
error in fish shell

### ISSUE THREAD

**Issue by c02y** [skywind3000/z.lua#13]
After doing the instructions in README.md, the following error message shows up:

`- (line 1): The file “” is not executable by this user
begin; '' '' --add /home/echecod/Public
       ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

in function “_zlua_call”
        called on line 13 of file -
        with parameter list “  --add /home/echecod/Public”

in function “_zlua”
        called on line 59 of file -
        with parameter list “--add /home/echecod/Public”

in function “_zlua_precmd”
        called on standard input

in event handler: handler for generic event “fish_prompt”

`

**Comment by skywind3000** [comment]
fish version ?? 2.4.0 is required, 2.7.0 is recommended

**Comment by c02y** [comment]
Sorry, forget to mentions the version:

    fish, version 2.7.1

**Comment by skywind3000** [comment]
Would you please run:

    lua /path/to/z.lua --init fish 

and provide the generated script please.

**Comment by c02y** [comment]
Sorry about this, it works now, I guess it was the problem of my fish session.

And z.lua can work across sessions, that is great. Thanks.
