### ISSUE TITLE
New z.lua version bumps major number

### ISSUE THREAD

**Issue by bayandin** [skywind3000/z.lua#130]
Hello,

I've noticed that the latest git tag of z.lua is `2.8.13` and the previous one is `1.8.12`. Could you please confirm if this is an intended bump of a major version (along with a patch version) or it's a typo and the new tag should be `1.8.13`.

Thanks!

Ref https://github.com/Homebrew/homebrew-core/pull/71152

**Comment by skywind3000** [comment]
sorry, it was a typo, fixed.

**Comment by bayandin** [comment]
No problem!
Thanks for fixing it so fast
