### ISSUE TITLE
Path exists but os.rename returns code 17

### ISSUE THREAD

**Issue by FlTr** [skywind3000/z.lua#136]
Hi,

Even so the paths exist (mapped network drives), they are not identified as such.

os.rename in os.path.exists returns code 17 which is not interpreted as valid. Corresponding error message is "File exists".

Environment:
* Win10
* Cmder 1.3.118
* lua 5.4.2
* z.lua 1.8.12

**Comment by skywind3000** [comment]
I don't have a network drive. Can't confirm if a new patch works.
So, PR is welcome.

**Comment by FlTr** [comment]
#138 fixed this issue.
