### ISSUE TITLE
powershell下只有一个路径

### ISSUE THREAD

**Issue by pengwon** [skywind3000/z.lua#146]
win10，powershell7
安装后执行`z`，列表中只有当前用户目录。多次使用cd到别的目录，然后再执行`z`，还是只列出一个路径。

**Comment by pengwon** [comment]
将powershell的$PROFILE中，starship和z.lua的配置行调换下位置，starship在前面，就好了。

**Comment by skywind3000** [comment]
说明 starship 破坏了 prompt 啊。

**Comment by pengwon** [comment]
> 

感谢说明解答
