### ISSUE TITLE
z.lua can't use - char ?

### ISSUE THREAD

**Issue by rfyiamcool** [skywind3000/z.lua#150]
when i input `z go-tracer` command, z.lua can't switch the path i want.  so z.lua can't support name don't contains `-` char ? 😁  This is a marginal need. 

![image](https://user-images.githubusercontent.com/3785409/154185083-59200313-7647-45dc-a44c-fad459931cb9.png)

**Comment by skywind3000** [comment]
https://github.com/skywind3000/z.lua/wiki/FAQ#how-to-input-a-hyphen---in-the-keyword-

**Comment by rfyiamcool** [comment]
好，谢谢大佬
