### ISSUE TITLE
如何修改权重

### ISSUE THREAD

**Issue by longcp** [skywind3000/z.lua#162]
请问如何修改某个路径的权重呢？看readme以及z -h里没有写。
做一个新项目的时候，项目里的目录结构和旧项目的结构一样，每次z xxx都会因为新项目目录权重不够，导致跳到旧项目里的目录。
所以想请教个手动增加某个目录权重的方法，感谢。

**Comment by colorsakura** [comment]
![image](https://user-images.githubusercontent.com/32534829/197989762-d365269e-90c0-45df-9cdd-845a515bfd04.png)

默认数据位置在 ~/.zlua
路径 | 权重 | 不清楚

**Comment by skywind3000** [comment]
时间戳
