### ISSUE TITLE
文件名中有-时不能正常切换

### ISSUE THREAD

**Issue by nick357** [skywind3000/z.lua#168]
环境：zsh
比如cd过 dot-zsh 这个目录，用z命令也能查看到改目录已经加入到列表。
z zsh，然后tab也能展开到该目录。
但z dot-zsh回车不能正常进入。用tab也无法展开到该目录。

**Comment by skywind3000** [comment]
你输入的是 lua 正则，减号在 lua 正则里是保留字，你可以用 `%-` 来代替，或者初始化前

    export _ZL_HYPHEN=1

这样就会自动将 `-` 转换成 `%-` 了。

**Comment by nick357** [comment]
感谢回复，问题解决
