### ISSUE TITLE
`z foo` takes me to `/foo/bar` instead of to `/foo`

### ISSUE THREAD

**Issue by devkvlt** [skywind3000/z.lua#172]
I guess this happens because I cded into `/foo/bar` more often, but is this normal behaviour? Is there a fix?

**Comment by ilyagr** [comment]
Try `z foo$`. `z` takes Lua regular expressions.

**Comment by skywind3000** [comment]
use the enhanced mode.

**Comment by devkvlt** [comment]
Fixed. Thanks a lot.
