### ISSUE TITLE
反馈：效果很差，比不上简单的z.sh

### ISSUE THREAD

**Issue by Rockyzsu** [skywind3000/z.lua#173]
安装的时候耗费了不少时间，后面使用正确率太低了，除了一两次跳转正常，
大部分时候跳转不到正确的目录，

系统ubuntu 20.04
shell zsh

**Comment by skywind3000** [comment]
算法都是基于 frecent ，跳转不到正确目录可能是你权重训练不够，你可以用两个关键字，写部分即可，再，可以尝试
增强模式，这个比 z.sh 好用多了：

    eval "$(lua /path/to/z.lua  --init zsh once enhanced echo)"

https://github.com/skywind3000/z.lua/blob/master/README.cn.md#%E5%A2%9E%E5%BC%BA%E5%8C%B9%E9%85%8D%E7%AE%97%E6%B3%95

**Comment by Rockyzsu** [comment]
每天cd进入某个目录，个人觉得频率很高的了。但z还是给我进入到home。

ps: star并不代表好用；我有一个近4K star的项目；但里面代码烂如泥 (⊙o⊙)

**Comment by skywind3000** [comment]
你的 z.lua 的初始化代码是？你想进的目录是？你打的命令是？
