### ISSUE TITLE
Looking for ~/.local/bin/lua

### ISSUE THREAD

**Issue by xuan-w** [skywind3000/z.lua#180]
Problem:

Add z.lua to bashrc using `eval "$(lua ~/path2z.lua/z.lua  --init bash once enhanced)"` . Bash started normally, `z` command is available. 
However, when I try to call `z` command, I got this error: 
```
-bash: /home/username/.local/bin/lua: No such file or directory
```

Expected behavior: 

No error. 

System Information:
WSL on Windows 10, Ubuntu 22.04
lua 5.4, installed to /usr/bin/lua. 

After I `ln -s /usr/bin/lua /home/username/.local/bin/lua`, I can use `z` command. But this shouldn't be the right way to solve this.

**Comment by skywind3000** [comment]
add this:

```bash
export ZLUA_LUAEXE=/path/to/your/lua/executable
```

after `eval "$(lua ...)"`

**Comment by skywind3000** [comment]
something wrong when getting the absolute path of your lua executable, you can try the above work-around, or try to execute lua with its absolute path name, like:

```bash
eval "$(/usr/bin/lua ~/path2z.lua/z.lua  --init bash once enhanced)"
```

**Comment by xuan-w** [comment]
Thank you! This solved my problem. 

I encountered another strange situation today, not sure if it is relevant. 
I saw 4 lua processes with high CPU usage even when all terminals were shutdown. In my four years of using your z.lua, I have never seen this. Then I run `pkill lua` to kill them all. 
I haven't been able to reproduce this.

**Comment by xuan-w** [comment]
It seems that my z.lua does have some problem. 

I removed ~/.zlua, but it never regenerate. Instead, whenever I cd to a directory, there is a new lua5.4 running, they never quit. 

Could you let me know how can I debug this? Thank you!

**Comment by xuan-w** [comment]
After installing `sudo apt-get install lua-filesystem`, high CPU usage problem is solved.
