### ISSUE TITLE
dirstack shows the frecency rather than index while using powershell

### ISSUE THREAD

**Issue by themql** [skywind3000/z.lua#184]
When I type `z --`, and the result is just likefollowing pic:

![image](https://github.com/skywind3000/z.lua/assets/61418658/dc77de15-d3d3-42cd-b418-fb9a035c8dfd)

Is there some config i have missed?

**Comment by skywind3000** [comment]
because powershell uses an ugly escaping rule, you need quote them:

    z "--"

or make an alias for it.

**Comment by themql** [comment]
thanks, i works

**Comment by riotrah** [comment]
Can we add a note in the documentation about this?
