### ISSUE TITLE
z ~ 存在问题

### ISSUE THREAD

**Issue by chenyucheng0503** [skywind3000/z.lua#188]
多次cd到根目录, 包括`cd ~` & `cd /Users/user1`
但是`z -l` 中从未出现 `~` 以及 `/Users/user1`
导致`z ~`时永远只跳转到权重高的子目录

**Comment by skywind3000** [comment]
用户目录是特殊目录，经常访问，一万种方法瞬间回去，
故不会记录数据库。

**Comment by chenyucheng0503** [comment]
好吧，如果习惯了使用z来切换目录，切换到用户目录还是希望能使用z命令
目前的解决方法就是用 `alias zz="cd ~"` 代替了

**Comment by skywind3000** [comment]
z ~ 是可以直接到用户目录的。

**Comment by kang8** [comment]
直接 `cd` 即可回到 home 目录

**Comment by chenyucheng0503** [comment]
> z ~ 是可以直接到用户目录的。

我本地测试不行，只会跳转到权重最高的~/子目录

> 直接 `cd` 即可回到 home 目录

第一次知道，感谢
