### ISSUE TITLE
i want to change the default z command to j ,but it doesn't work

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [skywind3000/z.lua#19]
mac, on-my-zsh, config as you say `export _ZL_CMD=j`.
i have test in a lua script `print (os.getenv('_ZL_CMD')` and it output 'j'.
when i type `j path` , i get `zsh: command not found: j`

**Comment by skywind3000** [comment]
It can't be reproduced on my laptop.

![rename](https://user-images.githubusercontent.com/3035071/52126254-ccbef900-2669-11e9-8c1b-9297b0ff3ae4.png)

1. switch to zsh
2. export _ZL_CMD=j
3. eval ...

and command 'j' is ready.

What is your setup step ?  Did you setup z.lua from a package manager ? Did you export `_ZL_CMD` before eval ?

**Comment by FinallyFinancialFreedom** [comment]
sorry my fault, i export _ZL_CMD just after eval. now it works ,thanks

**Comment by FinallyFinancialFreedom** [comment]
sorry my fault, i export _ZL_CMD just after eval. now it works ,thanks
