### ISSUE TITLE
.zlua file is always empty

### ISSUE THREAD

**Issue by owenstake** [skywind3000/z.lua#193]
.zlua file is always empty. How to debug it?

lua version:  Lua 5.4.6

system info:
cat /etc/deepin-version
[Release]
Version=20
Type=Professional
Edition=Y2020E0001
Copyright=Y2020CR001
[Addition]
Milestone=
Buildid=build1

**Comment by skywind3000** [comment]
are you using z.lua in WSL ??

**Comment by owenstake** [comment]
> are you using z.lua in WSL ??

No. Do you have some ideas to debug it?

**Comment by skywind3000** [comment]
what shell are u using ? how do you setup z.lua ?

**Comment by owenstake** [comment]
> what shell are u using ? how do you setup z.lua ?

reinstalll fix it

**Comment by owenstake** [comment]
`echo $_ZL_DAT`  can debug it.
