### ISSUE TITLE
刚使用，发现个小问题

### ISSUE THREAD

**Issue by Yggdroot** [skywind3000/z.lua#2]
我有路径`~/home/workspace/testFuzzyMatch` 和 `~/home/workspace`，当在~执行命令: `z wo` 时，路径切到`~/home/workspace/testFuzzyMatch`，而我想切到`~/home/workspace`，而且我认为后者更匹配。

z.sh 可以做到。

**Comment by skywind3000** [comment]
因为 `~/home/workspace/testFuzzyMatch` 的权重比后者高，你可以用：

```bash
z -l wo
```

查看当前权重，你当时用 z.sh 时，后者权重比较高而已。你可以多去一下第二个目录，再 `z wo` 时就会如愿跳转到第二个目录了。

数据库里统计了每条路径的 rank（访问多少次）和 time（上一次访问的时间），然后计算 frecent：

- 一小时内访问过：frecent = rank * 4
- 一天内访问过：frecent = rank * 2
- 一周内访问过：frecent = rank / 2
- 超过一周：frecent = rank / 4

此外，还有两个方法帮助你精确跳转：

首先关键字和 z.sh 一样支持正则，也就是说你可以显示指明 `z space$` 来匹配以 space 为结束的路径名。

其次你可以用 z.lua 里的 'z -i' 对多个结果开启 ”交互式选择“ ，如果 `z -i wo` 存在多个结果，会打印出来让你做一个选择。这个是我新加的，原版的 z.sh 没有这个功能，从 fasd 那里学习的。可以 alias 成：

    alias zz='z -i'

**Comment by skywind3000** [comment]
另外 z.lua 在 zsh 下面补全效果非常不错，你可以试试：

```bash
z wo<tab>
```

看看，z.sh 的补全有 bug，基本不能用。

**Comment by Yggdroot** [comment]
我知道是因为 `~/home/workspace/testFuzzyMatch` 的权重比较高，我的意思是可以参考z.sh做些改进。
我又反复进入 `~/home/workspace`进了几次，权重还是没有`~/home/workspace/testFuzzyMatch`高。
还有个极端的情况，如果我当前就在`~/home/workspace/testFuzzyMatch`，我使用`z wo`，这肯定应该跳到别的目录，但你的算法还是在当前目录。当然，这种情况可以特殊处理。
你说的正则表达式和`-i`是不错，但这往往需要多按一些字符，而我更喜欢最基础的`z dir`。
还有个需求，如果能进入某个目录后，自动再ls一下就更好了。
我再仔细比较比较。

**Comment by skywind3000** [comment]
$_ZL_CD 变量可以设置成你自己的 cd 命令，比如：

```bash
my_cdfunc() {
    cd "$1"
    ls -l
}

_ZL_CD=my_cdfunc
eval "(lua /path-to/z.lua --init bash)"
```

或者你可以打开

    _ZL_ECHO=1

让 z.lua 每次显示切换后的路径名，和 autojump 一样。

**Comment by skywind3000** [comment]
其他所有算法都和 z.sh 类似，唯一不同是 z.sh 会再多个匹配中求一个 common prefix，你这种情况下

    /home/workspace

就是一个 common prefix，z.sh 多个结果时会跳转过去。

这个做法再一些情况下会有问题，当初我详细比较过，所以我废除了这个功能，我自己经常用 $ 正则，所以用下来很顺，针对你这种情况，或者我参考 fasd 的做法，增加一个：

    _ZL_MATCH_NAME=1

选项，如果打开该选项，那么：

    z key1 key2 ...

最后一个 key 会严格匹配路径的名称部分，就最右边的 '/' 以后的剩余部分，那么

    /home/workspace/testFuzzyMatch    -> testFuzzyMatch
    /home/workspace                              -> workspace

这样打开这个选项后，你就能用

    z wo

如愿的跳转到 `/home/workspace` 了，和  fasd 的解决方案类似，这样如何呢？

**Comment by Yggdroot** [comment]
我觉得这样可以，不知道你说的严格匹配是什么意思，我想应该不是严格的前缀匹配，即如果是testWork，wo就匹配不上。
还有，上面我提到的，如果当前目录的路径最匹配，最好切换到次匹配的目录，即使_ZL_MATCH_NAME=0的情况下，因为既然使用z，肯定是想换个目录，而不是敲着玩。

**Comment by skywind3000** [comment]
已经更新，你可以测试：

```bash
_ZL_MATCH_NAME=1 z -l wo
z -l wo
```

两条语句的区别了，测试好以后，把加入到你的 `.bashrc` ：

````bash
export _ZL_MATCH_NAME=1
````

另外一个跳过当前路径的需求，配置叫做：

```bash
export _ZL_SKIP_PWD=1
```

**Comment by skywind3000** [comment]
没有改过，你可以
 
    z -l wo

看看权重到底是多少。

默认情况下，init 时没有加 once 的时候，hook 是放在 PROMPT_COMMAND 下面的，和 z.sh 行为相同，你每按一次回车，显示 PROMPT 前，当前路径再数据库里的 rank 都会 += 1

**Comment by Yggdroot** [comment]
不管了，现在已经满足我所有的需求了，很好用。
