### ISSUE TITLE
ohmyzsh 安装

### ISSUE THREAD

**Issue by entimm** [skywind3000/z.lua#20]
git clone https://github.com/skywind3000/z.lua $ZSH_CUSTOM/plugins/zlua

要把 omz.plugin.zsh 重命名成 zlua.plugin.zsh 才行

**Comment by skywind3000** [comment]
好的，我稍后改一下。

**Comment by skywind3000** [comment]
我用 antigen，名字乱起都行，只要有 .plugin.zsh 结尾的文件 antigen 就认了。

**Comment by skywind3000** [comment]
改好了，

git clone https://github.com/skywind3000/z.lua $ZSH_CUSTOM/plugins/z.lua

不叫 zlua 了。然后

plugins=( z.lua ) 

试试。
