### ISSUE TITLE
z cannot save other drive history in windows

### ISSUE THREAD

**Issue by Jaehaks** [skywind3000/z.lua#201]
thank you for your effort.

i am using z in windows 10 and cmd.
z works well in c:\  drive. but when i tour in d:\ drive, the history does not save in database 

could you fixed it?

**Comment by skywind3000** [comment]
Are you using z.lua with clink ? what is your lua version?

**Comment by Jaehaks** [comment]
I found the solution. 
If codepage of clink is 949, z list could not include non-english directory. 
I changed it to 65001

Control -> Language settings -> Administrative language settings -> change system locale 
=> check "Beta: User Unicode UTF-8 for world wide language support
