### ISSUE TITLE
--init show zsh: parse error near `>&' 

### ISSUE THREAD

**Issue by alps2006** [skywind3000/z.lua#205]
A strange problem on `z.lua --init`

```shell
z.lua$ eval "$(lua z.lua --init)" 
# output error
zsh: parse error near `>&'

```

I found the error location at `-h|--help) local arg_mode="-h" ;;`, and i resolved by escaping `--help` , but why only --help?

```diff
M z.lua
@@ -2188,7 +2188,7 @@ _zlua() {
 			-s) local arg_strip="-s" ;;
 			-i) local arg_inter="-i" ;;
 			-I) local arg_inter="-I" ;;
-			-h|--help) local arg_mode="-h" ;;
+			-h|\--help) local arg_mode="-h" ;;
 			--purge) local arg_mode="--purge" ;;
 			*) break ;;
 		esac

```

**Comment by skywind3000** [comment]
which version of zsh are you using?
I haven't encountered this before in zsh.

**Comment by skywind3000** [comment]
I am not sure if there is some side effect (mostly in other shells) when changing `--` to `\--`.
so I made another revise, please try out the latest version:

https://github.com/skywind3000/z.lua/commit/7c890c3645081014eab4be2ab45e8640f86f62d7

**Comment by alps2006** [comment]
I have found the reason why i cannot use `--help` only, because there is a global alias that overrides --help entirely.

```zsh
# bat to render --help
alias -g -- --help='--help 2>&1 | bat --language=help --style=plain'
```
thank you very much, i close it.
