### ISSUE TITLE
report error " _zlua:39: no such file or directory: /home/<my_username>/.nvm/versions/node/v16.16.0/bin/lua "

### ISSUE THREAD

**Issue by Liampor** [skywind3000/z.lua#207]
最近莫名出现的，每次运行 z.lua 都会提示这个，然而我看了另外一台电脑也是没有 lua 路径的但是工作正常，希望提供下解决思路 谢谢
![image](https://github.com/user-attachments/assets/96ae7423-125a-4384-9fef-2bd4bdc3ef23)

**Comment by skywind3000** [comment]
试试初始化时用 lua 的完整路径：

```bash
eval "$(/absolute/path/to/lua z.lua --init bash)"
```

是不是可以解决，不行的话，初始化后加一个：

```bash
ZLUA_LUAEXE=/path/to/lua
```

**Comment by Liampor** [comment]
使用第一个

> 试试初始化时用 lua 的完整路径：
> 
> ```shell
> eval "$(/absolute/path/to/lua z.lua --init bash)"
> ```
> 
> 是不是可以解决，不行的话，初始化后加一个：
> 
> ```shell
> ZLUA_LUAEXE=/path/to/lua
> ```

使用第一个方案完美解决问题，感谢作者🙏 🌷
