### ISSUE TITLE
[Feature Request] Support for Nushell?

### ISSUE THREAD

**Issue by brglng** [skywind3000/z.lua#208]
Any possibility to add support for [Nushell](https://www.nushell.sh/)?

**Comment by skywind3000** [comment]
最近有点忙，需要整块时间系统学习下 nushell 的 script 才行，如果你很熟悉 nushell 能否帮做个 PR？
就是加一段类似 bash/zsh 初始化的字符串，检测到 `--init nushell` 时返回就行了，参考 bash/zsh 代码如下：

https://github.com/skywind3000/z.lua/blob/7c890c3645081014eab4be2ab45e8640f86f62d7/z.lua#L2164-L2218

**Comment by brglng** [comment]
我也用得不久，还不能算很熟。不过有空我可以研究下怎么弄。

**Comment by skywind3000** [comment]
多谢！

**Comment by brglng** [comment]
已在 #210 合并了，所以先 close 了。
