### ISSUE TITLE
Cursor App 自动打开 z.lua 文件的问题

### ISSUE THREAD

**Issue by hahagood** [skywind3000/z.lua#211]
描述问题：
在使用 Cursor.AppImage (版本号: 0.44.9) 的过程中，每次启动应用程序时，它都会自动打开 ~/github/z.lua/z.lua 文件。即使没有任何相关设置或操作，这个文件也会被强制加载。为了解决这个问题，我只能暂时删除了该目录。

预期行为：
Cursor 应启动到默认空白页面，或者打开上次未关闭的文件，而不是强制加载特定路径的文件。

系统信息：
操作系统: Archlinux + i3wm
Cursor 版本: 0.44.9
文件路径: ~/github/z.lua/z.lua

复现步骤：
确保文件路径 ~/github/z.lua/z.lua 存在。
启动 Cursor.AppImage。
文件 ~/github/z.lua/z.lua 自动加载，无需任何操作。

尝试解决方法：
检查了 Cursor 的配置文件，未找到相关的文件路径设置。
删除了 ~/github/z.lua/ 目录，问题暂时消失。

附加信息：
这可能是 Cursor 的一个 Bug，或者与系统环境变量、文件路径解析有某种关联。如果需要更详细的信息或日志，请告知。

感谢您的开发工作！期待问题的修复！

**Comment by skywind3000** [comment]
我咋知道啊。
