### ISSUE TITLE
Fails on my Mac using ohmyzsh

### ISSUE THREAD

**Issue by indrayam** [skywind3000/z.lua#28]
I tried installing `z.lua` on my MacOS 10.14.3. I am running version `5.3.5` of `lua`.

**Installation steps:**
```
(cmd)>git clone git@github.com:skywind3000/z.lua.git .zlua
(cmd)>vim ~/.zshrc
```

Added the following lines at the end of `.zshrc`:
```bash
# Configure z.lua
eval "$(lua /Users/anasharm/.zlua/z.lua --init zsh)"
```

When I closed and restarted my iTerm, I get the following error:

```
/usr/local/bin/lua: /Users/anasharm/.zlua/z.lua:883: Is a directory
stack traceback:
	[C]: in for iterator 'for iterator'
	/Users/anasharm/.zlua/z.lua:883: in function 'data_load'
	/Users/anasharm/.zlua/z.lua:1137: in function 'z_add'
	/Users/anasharm/.zlua/z.lua:1605: in function 'main'
	/Users/anasharm/.zlua/z.lua:2336: in main chunk
	[C]: in ?
```

Any ideas?

**Comment by djarum-black** [comment]
On z.lua file, path is hardcoded on line 107:

`DATA_FILE = '~/.zlua'`

So it expects the file to be on user's home directory.

**Comment by skywind3000** [comment]
try:

    export _ZL_DATA=$HOME/.onfig/z.txt

**Comment by indrayam** [comment]
Thanks, @skywind3000 It works!

**Comment by perks** [comment]
what did you do?

`export _ZL_DATA=$HOME/.zlua/z.lua`
does not work
