### ISSUE TITLE
hangs fish

### ISSUE THREAD

**Issue by aeosynth** [skywind3000/z.lua#29]
Thanks for adding fish support, but when I use this, after `cd`ing once and then pressing enter, the prompt just hangs for a few seconds.

```
lua z.lua --init fish > ~/.config/fish/conf.d/z.fish
# open new terminal
cd dl
# press enter, hang
```

fish, version 3.0.0

**Comment by skywind3000** [comment]
strange. does fish have any profile tool ??

**Comment by skywind3000** [comment]
I can't reproduce it, could you try to modify your generated z.fish ??

https://github.com/skywind3000/z.lua/blob/56d56af771e99a55dbca9209749c516149fe618e/z.lua#L2004-L2014

change:

    _zlua --add "$PWD" 2> /dev/null &

to:

    _zlua --add "$PWD"

**Comment by skywind3000** [comment]
@TeddyDD, do you have any clue for this ??

**Comment by TeddyDD** [comment]
Works for me with this setup. @aeosynth does it work when you load script dynamically
```
$ cat ~/.config/fish/conf.d/z.fish
lua ~/Kod/z.lua/z.lua --init fish once enhanced | source
```

**Comment by aeosynth** [comment]
same issue with  dynamic loading, changing the generated `z.fish` doesn't help either.

debug output: https://gist.github.com/aeosynth/70acc5517b3c0217f539c45f2b87dcb4

**Comment by TeddyDD** [comment]
Tried to bisect that, first bad commit seems to be c88b8213c55418fcdd0faf3c032e001c897656e3 but I'm not entarily sure (it hangs but for shorter period of time than on master)

**Comment by skywind3000** [comment]
_zlua --add "$PWD" 2> /dev/null &

I am afraid that fish will wait for background job finished in the pipe. and somehow, the background job delayed. 

So I suggest to temporarily remove the `&` sign first.

**Comment by TeddyDD** [comment]
I removed & and I still can reproduce it.

> maybe plugin conflicts ??

no, tested with `sh -c 'env HOME=$(mktemp -d) fish'`, no custom scripts loaded

**Comment by skywind3000** [comment]
sad, still can't reproduce on my laptop, 

https://github.com/skywind3000/z.lua/blob/4c5d0aa40449d578164b9e40f8bb939dfcded53d/z.lua#L811-L823

If we remove line 815-819, do we still encounter this ?

even if it's a issue of fish, is there a way to prevent this ?

**Comment by TeddyDD** [comment]
Yeah, removing 815-819 seems to fix that issue, @aeosynth  could you confirm that?

**Comment by skywind3000** [comment]
ok, removed and updated, @aeosynth , could you please try the latest version ?

**Comment by aeosynth** [comment]
works great so far, thanks!
