### ISSUE TITLE
'popen' not supported

### ISSUE THREAD

**Issue by Yggdroot** [skywind3000/z.lua#3]
The readme says `compatible with lua 5.1, 5.2 and 5.3+`, but I got the following error when using.
```
lua: /home/.z.lua/z.lua:212: 'popen' not supported
stack traceback:
	[C]: in function 'popen'
	/home/.z.lua/z.lua:212: in function </home/.z.lua/z.lua:211>
	(...tail calls...)
	/home/.z.lua/z.lua:1400: in function 'z_shell_init'
	/home/.z.lua/z.lua:1135: in function 'main'
	/home/.z.lua/z.lua:1574: in main chunk
	[C]: in ?

```

lua -v
```
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
```
uname -a

```
Linux xxx 2.6.32-504.8.1.el6.x86_64 #1 SMP  x86_64 x86_64 GNU/Linux
```

**Comment by skywind3000** [comment]
io.popen 是 lua 源代码中的标准函数：
https://github.com/lua/lua/blob/28d829c86712ce5bc453feccc5129a32f78d80c0/liolib.c#L277

你这个版本的 lua 编译的时候没有打开 popen，就是个宏，默认是打开的：
https://github.com/lua/lua/blob/28d829c86712ce5bc453feccc5129a32f78d80c0/liolib.c#L55-L74

请调查一下你的

    LUA_USE_POSIX

或者

    LUA_USE_LINUX

为什么没有打开？

只要正常编译，这个宏都是打开的，你看我的lua：

```
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> print(io.popen('pwd'):read('*l'))
/home/skywind
>
```

**Comment by Yggdroot** [comment]
哦，那我重新编译一下。

**Comment by skywind3000** [comment]
https://github.com/lua/lua/blob/4ace93ca6502dd1da38d5c06fa099d229e791ba8/makefile#L56

恩，LUA_USE_LINUX 这个宏再 Makefile 里面默认是开启的，开启后，luaconf.h 中会根据这个宏打开

    LUA_USE_POSIX

然后就可以用 popen 了。
https://github.com/lua/lua/blob/4ace93ca6502dd1da38d5c06fa099d229e791ba8/luaconf.h#L61

**Comment by Yggdroot** [comment]
发现z.lua如果找不到匹配的路径，就呆在当前路径什么都不做。
可不可以有个这样的功能：当前路径有个目录叫aaa，我知道有这个目录，但是从没有进去过，我执行`z aaa`也可以进去。也就是说，如果找不到匹配的路径，就等同于cd。

**Comment by skywind3000** [comment]
恩，修改好了：

```bash
export _ZL_MATCH_MODE=1
```

默认 0 的匹配模式留给默认的原教旨主义匹配法吧，新的匹配法我都挪到 _ZL_MATCH_MODE=1 下面了，包括之前的两个宏都可以省略了。

**Comment by Yggdroot** [comment]
嗯， 好了。
