### ISSUE TITLE
Fails on mac with zsh

### ISSUE THREAD

**Issue by tradfursten** [skywind3000/z.lua#36]
I tried to initiate z.lua on my mac but I can't get it to work. I keep getting:
`_zlua:32: = not found`

In my .zshrc:
`eval "$(lua <home>/lib/z.lua/z.lua --init zsh)"`

lua version 5.3.5
Zsh version 5.3

**Comment by skywind3000** [comment]
Could you paste the output of:

    lua <home>/lib/z.lua/z.lua --init zsh

here ?

**Comment by skywind3000** [comment]
sorry, I have just added a new feature and introduced a typo in the bash script, but it works on my linux bash/zsh so I haven't noticed yet.

fixed, please update and try the latest version

**Comment by tradfursten** [comment]
It works now

**Comment by skywind3000** [comment]
Cool
