### ISSUE TITLE
[Feature Request] support hyphen (-) shortcut to go back last directory

### ISSUE THREAD

**Issue by adoyle-h** [skywind3000/z.lua#41]
It will be a nice feature to support the hyphen `-` as a shortcut.

The behavior of `z -` should be similar to `cd -`.

> An argument of - is converted to $OLDPWD before the directory change is attempted

The behavior of `z -i -` and `z -I -` should be similar to [`enhancd`](https://github.com/b4b4r07/enhancd). It will take a hyphen (-) string as an argument, it searchs from the last 10 directory items in the log. With it, you can search easily the directory you used last.

```
$ z -I -
  /home/lisa/Dropbox/etc/dotfiles
  /home/lisa/Dropbox
  /home/lisa/src/github.com
  /home/lisa/src/github.com/b4b4r07/cli
  /home
  /home/lisa/src
  /home/lisa/src/github.com/b4b4r07/enhancd
  /home/lisa/src/github.com/b4b4r07/gotcha
  /home/lisa/src/github.com/b4b4r07
> /home/lisa/src/github.com/b4b4r07/portfolio
  10/10
> _	
```

**Comment by skywind3000** [comment]
啊，我说中文吧，英文说的累，如果只是简单的跳转到 $OLDPWD 的话，`cd -` 似乎就够了，我多加一个 `z -` 好像并没有额外的价值。

你说的 `z -i -` 或者 `z -I -` 的确是比较方便，但是我不知道可以去哪里读取这个 cd 历史路径，如果没法读取，势必我需要维护一个 cd 的路径栈，然后模拟 pushd / popd 的动作，这可能会引入另外一个数据文件，如果要引入另外一个数据文件的话，我比较纠结。

再，zsh/fish 下面 `cd -<tab>` 都会列出一个最近访问列表，再按一次 tab 就可以选择了，是不是能 cover 这项需求？？

**Comment by adoyle-h** [comment]
@skywind3000 
我倾向于用 z.lua 替代掉 enhancd 和 cd，所以期望也支持 `-` 快捷键。如你所说没有额外的价值。
看了一眼 enhancd 的实现，的确引入了一个 [enhancd.log 文件](https://github.com/b4b4r07/enhancd/blob/master/src/history.sh#L12)。
我用的是 bash 4，enhancd 能满足功能，只不过我不想记太多命令，期望一个命令能集成所有功能。

**Comment by skywind3000** [comment]
我想起来了，数据文件里本来就有访问时间，你可以用 `-t` 参数，将排序权重由 frecent 改为时间，那么你的需求就可以用：
 
    z -i .

或者：

    z -I .

就行了，完全符合你的需求，你可以 alise 一下，取个两个字母的名字，随时呼唤出来。最好打开 enhanced 匹配模式，这样能在结果里把当前目录给过滤掉。

**Comment by skywind3000** [comment]
我更新文档了：

https://github.com/skywind3000/z.lua/blob/master/README.cn.md#mru

**Comment by adoyle-h** [comment]
@skywind3000 很酷，谢谢。纠正一下，文档里的 alias 命令用的是反引号，请用引号。

**Comment by adoyle-h** [comment]
Make a summary,
- No need `z -`, use `cd -` instead of.
- `z -I -` can be implemented with  `z -t -I .`.

**Comment by Yggdroot** [comment]
```bash
zlua()
{
    if [ -z "$@" ]; then
        cd
    elif [ "$@" == '-' ]; then
        cd -
    else
        z "$@"
    fi
}

alias j='zlua'
```

我写了这个函数来达到这个目的。

**Comment by skywind3000** [comment]
traditional hyphen has been introduced in [v1.5.1](https://github.com/skywind3000/z.lua/releases/tag/v1.5.1):

```bash
# display current dir stack
$ z --    
 0  /home/skywind/work/match/memory-match
 1  /home/skywind/.local/etc
 2  /home/skywind/software/vifm-0.9.1
 3  /home/skywind/work
 4  /home/skywind/work/match

# cd to the 2nd directory in the stack
$ z -2
  => cd /home/skywind/software/vifm-0.9.1

# popup stacktop (cd to previous directory), same as "z -0"
$ z -
  => cd -
```
