### ISSUE TITLE
Using regex with $_ZL_EXCLUDE_DIRS

### ISSUE THREAD

**Issue by luong-komorebi** [skywind3000/z.lua#43]
Currently I am excluding dirs with an array but I wonder if regex can be used instead. If possible, could you give me an example? Thank you for your helpful tool.

**Comment by skywind3000** [comment]
Please update to the latest version.

In the latest version, `$_ZL_EXCLUDE_DIRS` is a comma separated list of dirs, which can be defined as:

    export _ZL_EXCLUDE_DIRS="/home/user/exclude1,/home/user/exclude2,/home/user/exclude3"

The three directories `~/exclude1`, `~/exclude2` and `~/exclude3` themself and every child directory inside them will be excluded.

**Comment by luong-komorebi** [comment]
Thank you for your kind support. I was on the latest version (the one before you updated the readme). Now that I am on the latest one, let me share with you my use case. I want to exclude the `Google Drive` directory from z.lua.  It may be special because it contains space, but I can totally `cd $_ZL_EXCLUDE_DIRS` to it. Below is a gif describing my effort: 
![2019-02-12 22-00-31 2019-02-12 22_01_58](https://user-images.githubusercontent.com/15828926/52644823-277e0d80-2f12-11e9-914e-62a7220cf960.gif)

**Comment by skywind3000** [comment]
the string has already been quoted, the back slash is unnecessary, try to remove it:

    export _ZL_EXCLUDE_DIRS="/Users/eh/Google Drive"

**Comment by luong-komorebi** [comment]
Awesome. It works for me now. Thank you so much. ❤️
