### ISSUE TITLE
Omit the backtrace mesage when hitting Ctrl-c in interactive selection mode

### ISSUE THREAD

**Issue by c02y** [skywind3000/z.lua#45]
When using the interactive selection mode, at the prompt, I hit Ctrl-c to cancel, z.lua will print several lines of backtrace message which is unnecessary.

![qq](https://user-images.githubusercontent.com/2135996/52759244-22ba7600-3046-11e9-920a-57dbed2df02e.png)

Could you please omit this message just like hitting `Enter` key without typing any index from the list?

**Comment by skywind3000** [comment]
Sorry, stardard lua can't handle signal, it requires a third-party module called 'lua posix'.

**Comment by c02y** [comment]
Thanks, it works now.
