### ISSUE TITLE
[suggestion] cold start issue

### ISSUE THREAD

**Issue by jdhao** [skywind3000/z.lua#46]
After a fresh install of z.lua, in order to use it, the user have to use `cd` first to build the history, which is not very smart. Maybe you can directly read the user's command history to find those `cd` command and add the corresponding directories automatically. 

In this way, z.lua becomes smarter.

**Comment by skywind3000** [comment]
command history cannot be used, because most `cd` command in it are using relative path and it is impossible to extract absolute paths from command history.

**Comment by antonalekseev** [comment]
> impossible to extract absolute paths from command history

@skywind3000 Actually, this is not quite true given the fact that regular shell user uses completion which yields either absolute path or path relative to `$HOME` and then retrieves same commands from history. On the other hand, users who prefer `cd` dir-by-dir don't care about cold start at all.

I used the following commands to pre-warm my `.zlua` databases.

For zsh: `zsh$ fc -ln 0|grep -o "^cd [~/].*"|sed -e "s|cd ||" -e "s|~|$HOME|" -e 's|\\ | |' -e "s|/$||"|sort|uniq|while read -r d; do test -d "$d" && echo "$d|1|0"; done >> ~/z.lua`

For bash: `bash$ fc -ln -10000| sed -e 's|^'[[:blank:]]' ||'|grep -o "^cd [~/].*"|sed -e "s|cd ||" -e "s|~|$HOME|" -e 's|\\ | |' -e "s|/$||"|sort|uniq|while read -r d; do test -d "$d" && echo "$d|1|0"; done >> ~/z.lua`

The only problems with given statements are that usually shells don't store duplicates of commands so it's impossible to calculate weight, and those ones should be used only on empty database to avoid duplicate entries within `.zlua` (`>>` above provided to prevent user from ruining database by unwittingly copy-pasting given lines).

I even considered to submit PR to add those to `README` along with other import commands, but I'm not sure about elegance and portability of the shell statements above.

**Comment by skywind3000** [comment]
@antonalekseev Awesome ! I will quote this in readme.

**Comment by skywind3000** [comment]
I have mentioned this here:

https://github.com/skywind3000/z.lua/wiki/FAQ#how-to-import-data-from-bash--zsh-command-history-

thanks guys.

**Comment by skywind3000** [comment]
and it could be closed.
