### ISSUE TITLE
Directories changes won't affect the cd history of the fish shell

### ISSUE THREAD

**Issue by c02y** [skywind3000/z.lua#47]
fish v2.7.1
z.lua version: 5c2e0c6 

When using z.lua to change directories, it seems it won't affect the cd history of the fish shell, when I want to go back to the previous directory using command `cd -`, it says "Hit end of history…" and it is unable to go back. I know I can use `z -b` to go back to the history, but most of time `cd -` is much simpler.

But I tried it in bash shell, it works as expected.

**Comment by skywind3000** [comment]
Because z.lua uses `builtin cd`, the builtin cd in fish won't update dir stack. I can reproduce it for you:

```bash
skywind@weilin0:~$ fish
skywind@weilin0 ~> builtin cd /tmp
skywind@weilin0 /tmp> builtin cd /usr
skywind@weilin0 /usr> cd -
Hit end of history…
skywind@weilin0 /usr> cd /tmp
skywind@weilin0 /tmp> cd /usr
skywind@weilin0 /usr> cd -
skywind@weilin0 /tmp>
```

You can define a `_ZL_CD` to customize your cd command, for example, initialize _ZL_CD as `cd` will use `cd` directly.

**Comment by c02y** [comment]
Thanks.

    set -gx _ZL_CD cd

in config.fish works.
