### ISSUE TITLE
sort the path in the list 

### ISSUE THREAD

**Issue by c02y** [skywind3000/z.lua#51]
Currently z.lua couldn't sort the path in the list, so when some subdir entries in the list, they will be in different places, it's hard to find what I want from the messed-up list.

So please add a option for z.lua to sort the path. It is very useful when using `z -I` or `z -i`(fzf itself sorts the path by default, but it doesn't work with z.lua).

**Comment by skywind3000** [comment]
The directories passed to fzf are sorted by `frecent`, because fzf can only sort data by string comparison. 

FZF will not consider the times you have visited one directory and when is your last access time. So keep them sorted in `frecent` is convenience because the directory you are most likely to use will get a higher rank.

see: https://github.com/skywind3000/z.lua/wiki/Effective-with-fzf

**Comment by skywind3000** [comment]
You can override fzf's parameter by setting `_ZL_FZF_FLAG`. the default value is `+s -e`. you can change to:

```bash
export _ZL_FZF_FLAG="-e"
```

**Comment by skywind3000** [comment]
You can even define a new function (I don't know how to implement in fish) by combine `z -l` and `fzf`:

```bash
function zf2() {
    local $dest="$(z -l "$@"|fzf --nth 2 --reverse --inline-info --tac +s -e --height 35%)"
    [ -n "$dest" ] && cd "$dest"
}
```

**Comment by c02y** [comment]
It seems neither _ZL_FZF_FLAG='-e' or zii works.

The results are the same:

~~~
$ z -l . |fzf --nth 2 --reverse --inline-info --tac +s -e --height 35%                                                                                                                                               (7s 198ms)[17:18:49]
>   < 18/18
> 160        /home/echecod/Dotfiles.d/fish/.config/fish/functions
  88         /home/echecod/tb5g_leap_ricn/leap_build/submodules/rua/src
  66         /home/echecod/tb5g_leap_ricn.bak/leap_build/submodules/rua
  38         /home/echecod/tb5g_leap_ricn.bak/leap_build/submodules/rua/src
  32         /home/echecod/Public
  12         /home/echecod/anaconda3/bin
  4          /home/echecod/.emacs.d
  3          /home/echecod/.emacs.d/elpa
  2.5        /home/echecod/test
  2.5        /home/echecod/Dotfiles.d
  2          /home/echecod/tb5g_leap_ricn/leap_build/leap_app_src/src/dua-boot/src/boot/conf
  2          /home/echecod/tb5g_leap_ricn.bak
  1          /home/echecod/Dotfiles.d/fish/.config/fish
  1          /home/echecod/tb5g_leap_ricn
  0.5        /home/echecod/anaconda3/share/fish
  0.5        /usr/share/fish
  0.5        /home/echecod/Dotfiles.d/fish/.config
~~~

**Comment by skywind3000** [comment]
no, you need type some character, the result is sorted. or use:
 
    z -l -s . | sort | fzf --reverse --height 32

**Comment by c02y** [comment]
> no, you need type some character, the result is sorted. or use:

You mean like

    
![qq](https://user-images.githubusercontent.com/2135996/53083206-6545ec00-3539-11e9-82a8-c0dd4a6c417c.png)

It is still not sorted.

Anyway `z -l -s .` seems work correctly.
![qq](https://user-images.githubusercontent.com/2135996/53083262-84447e00-3539-11e9-9102-2995e5b44bc3.png)

**Comment by skywind3000** [comment]
check if fzf executable is in the $PATH

**Comment by c02y** [comment]
Note that I've updated a little bit in my previous reply.

> check if fzf executable is in the $PATH

This is my zz function:

~~~
function zz -d 'z\'s interacgive selection mode'
    fzf-p
    if test $status = 0 # fzf exists
        set z_cmd z -I
    else
        set z_cmd z -i
    end
    if test (count $argv) = 0
        eval $z_cmd .
    else
        eval $z_cmd  $argv
    end
end
~~~

`fzf-p` is another function I defined to check the existence of fzf file, it not, download from github release page and extract it to my $PATH, but if there is internet connection problem, I'm available to use fzf, then I have to use `z -i` which is builtin interactive mode of z.lua.

**Comment by skywind3000** [comment]
checkout v1.5.6:

new: set `$_ZL_FZF_SORT` to 1 to sort directories by alphabet in fzf.

**Comment by c02y** [comment]
OK, I'll try it tomorrow. Thanks.

BTW, there is no explanation for option `-s` for `z` command in README.md or `z --help`.

**Comment by skywind3000** [comment]
`-s` means strip, `z -l` will display a score column while `z -l -s` outputs directories only.

it came with v1.1.0, just undocumented.

**Comment by c02y** [comment]
Yeah $_ZL_FZF_SORT  works, but builtin interactive selection mode is not sorted. Is it able to sort the path in builtin interactive selection mode too? And then replace the _ZL_FZF_SORT varibale with something like _ZL_SORT, not just for fzf, but for z command itself

![qq](https://user-images.githubusercontent.com/2135996/53138800-725aed80-35c2-11e9-8dac-c65aeb6e9fb9.png)

**Comment by skywind3000** [comment]
checkout v1.5.7, use `$_ZL_INT_SORT` instead.

**Comment by c02y** [comment]
Thanks. but now, sorting orders of `z -i .` and `z -I .` are opposite, I think they should be the same order.

**Comment by skywind3000** [comment]
That requires a big refactor.

**Comment by c02y** [comment]
Big refactors for both `z -i .` and `z -I .`? I thought sorting is a simple thing, like `sort` command with an option, I don't need specific order, the same order would be OK, not matter a->z or z-a, of course, if the order can be chosen, that would be better.

**Comment by c02y** [comment]
And another thing is, the prompt symbol `>` for interactive selection mode, by default, it is in the bottom in `z -i`, but it is the top in `z -I`, would you please make it the same?

**Comment by skywind3000** [comment]
`z -i` will list directories in ascending order, directory with highest frecency will likely to be selected, so it will be listed in the bottom, close to the `>` sign. Since z.lua can't scroll the terminal screen, directories with lower frecency will likely to be ignored so they will be listed first.

So, the best experience for `z -i` is to list directories in ascending order and display the `>` at the bottom.

**Comment by skywind3000** [comment]
`z -I` is using fzf, listing directoies in descending order is very strange in fzf.

It's okay if you input nothing:

![strange1](https://user-images.githubusercontent.com/3035071/53224720-a7456e00-36b0-11e9-9e98-55d551926b55.png)

But if you input some keywords:
![strange2](https://user-images.githubusercontent.com/3035071/53224738-b2989980-36b0-11e9-8d1a-b4cbf0f718b9.png)

There will be a noticable blank gap between command you just input and the cursor. Seems very strange, so, the best experience to use fzf is using `--reverse` parameter.

**Comment by c02y** [comment]
OK, then.

So, could this issue page be closed now? I'm not sure whether you would add something mentioned in the page into z.lua or not.

**Comment by skywind3000** [comment]
Let's close this now before we have a better solution.
