### ISSUE TITLE
The number of entries in the list of `z -I .` shouldn't be fixed

### ISSUE THREAD

**Issue by c02y** [skywind3000/z.lua#52]
I just noticed something in the following image, that the list of `z -I .` doesn't list **all** the entries in database like `z -i .` does, there is plenty extra place in my terminal, maybe you shouldn't hard-code the number of entries in the database, but list the entries as many as possible according to the size of terminal screen, or you can give us an variable so we can choose the number we want. (I personally prefer the first solution.)

![qq](https://user-images.githubusercontent.com/2135996/53142007-3ed19080-35cd-11e9-9061-efa64bbc3aee.png)

**Comment by skywind3000** [comment]
checkout v1.5.8

**Comment by c02y** [comment]
Thanks.
