### ISSUE TITLE
匹配对带横杆的路径失败

### ISSUE THREAD

**Issue by AlexZhong22c** [skywind3000/z.lua#53]
环境：macosx 10.12.6; 命令行：zsh

usage: 添加`eval "$(lua $HOME/.oh-my-zsh/custom/plugins/z.lua/z.lua --init zsh)"`到.zshrc，普通模式

------

比如说我有一个目录是` ~/Documents/github/vue-my-ui`，路径是带横杆的，我想跳到这路径：

case1：使用`z vue`能跳转，使用`z vue-my-ui`不能跳转到对应目录。

case2：使用`z -l vue`能list出来，使用`z -l vue-my-ui`不能出来。

case3：使用`z -l github/vue`能list出来，使用`z -l github/vue-my-ui`不能list出来。

其他的z指令都是这样，不知道是不是我用法有问题，只要搜`路径带横杆`的，都搜不出来。

**Comment by AlexZhong22c** [comment]
我知道了，那片地方需要输入的是正则，而不是可输入正则。在正则中需要转义的都要转义。比如横杆`-`必须要写成`\\-`

**Comment by AlexZhong22c** [comment]
用正则`z \\-ui$`可以搜到，但是`z vue\\-my\\-ui`不行

**Comment by skywind3000** [comment]
所有关键字都是 lua 正则表达式，文档里说过了，横杆是关键字，
要写成 `vue%-my%-ui` 才行，所以你可以

    z vue%-my%-ui

或者干脆用多个空格分隔的关键字，比如：

    z vue my ui

就行了。
