### ISSUE TITLE
'z -b' should not match current directory

### ISSUE THREAD

**Issue by networm** [skywind3000/z.lua#56]
## Version
Version 1.5.8, Last Modified: 2019/02/21 12:08

## Environment
- macOS 10.14.3
- fish 2.6.0
- zsh 5.7.1

## Step
```bash
$ mkdir -p a/b/c/d/a
=> ~
$ cd a/b/c/d/a
=> ~/a/b/c/d/a
$ z -b a
=> ~/a/b/c/d/a
$ z -b b
=> ~/a/b
```

## Problem
`z -b a` should jump to `~/a`, but it stays at `~/a/b/c/d/a`.

`z --help` has mentioned that cd to the parent directory.
```
z -b foo    # cd to the parent directory starting with foo
```

I think 'z -b' should not match current directory.

**Comment by skywind3000** [comment]
fixed in v1.5.9
