### ISSUE TITLE
What time to support the use of the brew installation?

### ISSUE THREAD

**Issue by banduoba** [skywind3000/z.lua#57]
What time to support the use of the brew installation?

**Comment by skywind3000** [comment]
我没有 mac，如果有人能帮做一下的话，非常感谢。

**Comment by mathomp4** [comment]
@skywind3000 One possibility would be to try and make a new package in [Linuxbrew](http://linuxbrew.sh/), their Linux version of brew. From what I can see, their docs for Linuxbrew are the same docs as Homebrew, so the [Formula Cookbook](https://docs.brew.sh/Formula-Cookbook) should hold for either.

I might try to figure it out on my Mac, but I'd be more confident if I could find a package similar to z.lua currently in brew. I suppose something like [ack](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ack.rb) is similar as it has no "build" step, and it looks like the [Linuxbrew ack Formula](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/ack.rb) is quite similar.

**Comment by albertofwb** [comment]
@banduoba 
oh-my-zsh plugin: *zsh-autosuggestions* is similar to z.lua

**Comment by banduoba** [comment]
@albertofwb thank you

**Comment by theonlygusti** [comment]
Please add a homebrew installation method
