### ISSUE TITLE
Compatibility with fzf z integration

### ISSUE THREAD

**Issue by balta2ar** [skywind3000/z.lua#58]
I'm using this fzf+z integration https://github.com/junegunn/fzf/wiki/examples#z:
```bash
unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}
```
How do I adjust it for z-lua? The problem is that I want to have "z" alias to always call fzf, and I should save it with a different name somehow (it's "_z" in the above example). Thanks!

**Comment by skywind3000** [comment]
replace `_z` with `_zlua` will work for zlua, but I suggest you use:

    alias zz='z -I'

zlua has already integrated fzf in `z -I`

**Comment by balta2ar** [comment]
Thanks for the tip! I've been typing just `z` for years already and I don't think it's gonna be easy for me to break my habit and start typing `zz`... which is twice as long!

Sorry for the unrelated question, but does z.lua suffer from race conditions similar to this one: https://github.com/rupa/z/issues/198? It's important to know before I make a switch.

**Comment by skywind3000** [comment]
z.lua uses a temporary for writing, and then a `rename()` syscall to override the old database file atomicly.

If another instance is reading the old database file while `rename` happened, the inode of `.zlua` database will be updated immediately but the reading process will continue reading the old one.

It was guaranteed by posix  specification and linux implementation, see here:
https://unix.stackexchange.com/questions/322038/is-mv-atomic-on-my-fs

**Comment by skywind3000** [comment]
If you are still worry about that, feel free to enable the "add once" flag:

    eval "$(lua /path/to/z.lua --init bash once ....)"

**Comment by balta2ar** [comment]
Thanks again!
