### ISSUE TITLE
Can not add symbolic link folder to history

### ISSUE THREAD

**Issue by fcying** [skywind3000/z.lua#59]
```
mkdir t2
ln -s ~/test/t2 t3
cd t2
cd ../
z | grep t2
4          /home/fcying/test/t2
cd t3
cd ../
z | grep t3
//nothing
```

**Comment by skywind3000** [comment]
system ？

**Comment by fcying** [comment]
```
uname -a
Linux nas 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

zsh --version
zsh 5.3.1 (x86_64-debian-linux-gnu)

export _ZL_FZF_FLAG="-e"
eval "$(lua $HOME/bin/z.lua --init zsh once enhanced)"
```

**Comment by skywind3000** [comment]
应该是 os.path.isdir 检测失败了，然后被当成非法路径给过滤掉了。你可以翻翻 z.lua 里的 os.path.isdir 实现，这应该是lua不接任何第三方库情况下能做到的极限了。

**Comment by fcying** [comment]
加了些log. 是`os.path.exists` 里的问题, 软连接的 `os.rename` 返回值 `code` 是20, 后面没判断这个. 我加个20的判断.. 你看看会不会影响到别的?
```
name:   /home/fcying/test/t3/   exist:  false
nil     Not a directory 20
```

**Comment by skywind3000** [comment]
你光检测 20 不行的，20 的意思是：
not a directory
不是目录，是文件也会返回 20，所以还需要进一步加点判断。

我已经改好了，验证下。

**Comment by skywind3000** [comment]
又更新了一下，cygwin/freebsd 的错误码不一样

**Comment by fcying** [comment]
debian上工作正常.

P.S. 能不能出个 `z -d ~/test/t2` 之类的命令删除 `.zlua` 里面的历史, 直接`vim ~/.zlua` 修改不够方便

**Comment by skywind3000** [comment]
有的啊：

    z -x {绝对路径}

**Comment by fcying** [comment]
原来已经有了....只看了 `Examples` 没看help@_@

试了一下. 没删掉(直接看的.zlua), 而且`z -x`后 会直接跳到要删除的目录去
```
~ $z -x /home/fcying/test/t2
~/test/t2 $
```

**Comment by skywind3000** [comment]
那是因为 z 命令被你重新定义过吧？

**Comment by fcying** [comment]
的确是这样....用了`fz`
```
which z
z: aliased to _fz

function _z() { _zlua "$@"; }
```

把 z -x 改成`alias zx='_zlua -x'` 就好了...

**Comment by fcying** [comment]
用 `alias zx='_zlua -x'` 有个奇怪的问题. 输入 `zx ~/<tab>` 弹不出补全了...

用 `alias zx='_z -x'`, `zx ~/<tab>` 就能正常补全目录
