### ISSUE TITLE
Not work on git bash windows 下的git bash中不生效

### ISSUE THREAD

**Issue by sherylynn** [skywind3000/z.lua#63]
I had try normal bash --init and normal z.cmd way
but both not work
when use normal bash init， it print out no setlocal
when use z.cmd no printout and don't change dir
我尝试了--init bash的方法，也尝试了添加clink到path变量的z.cmd方法，但是不生效
前者依然识别为windows下，我查看了z.lua中的windows判断，似乎不受eval "$(lua /path/to/z.lua --init bash enhanced)"而单独设置local windows的true和false，但git bash在windows是否可以按照常规bash来处理的，因为如果用z.sh，git bash是可行的
而z.cmd为啥在git bash中直接没有输出，也没有目录切换，我暂时没有看出问题

**Comment by skywind3000** [comment]
你需要编译一个 msys32 的 lua 给 git-bash 用，而不是用 windows 版本的 lua。

**Comment by sherylynn** [comment]
> 你需要编译一个 msys32 的 lua 给 git-bash 用，而不是用 windows 版本的 lua。

我使用的https://sourceforge.net/projects/luabinaries/下的lua执行程序，看上面说明是mingw生成的，理论上应该和msys32兼容的呀

**Comment by skywind3000** [comment]
错了，你就没搞懂 msys32 和 mingw32 的区别。git-bash 是一套 msys32 系统，它上面运行的 bash，vim 这些工具都是再 msys32 的虚拟 unix 环境中运行的，对他们来说，路径都是 unix 路径，c 盘某路径是：
`/c/windows`，而 mingw32 程序，是标准的 windows 程序，他们认为，c 盘是：`c:\windows`。

你需要的是 msys32 的 lua，而不是 mingw32 的 lua

**Comment by sherylynn** [comment]
我下载了msys2，
试过通过pacman -S 安装的lua，但这个lua也是只能在mingw的shell里调用的，而且不能使用z.lua。会提示stdout is not a tty。
然后我按您教的下载lua源码在msys2里使用msys2/gcc编译，看到make 选项里是默认有支持mingw的platform的，但是没有列出msys2，单纯make mingw后的可执行程序拿到git-bash中后，z.lua依旧会这样提示
`lua: ./z.lua:278: 'popen' not supported
stack traceback:
        [C]: in function 'io.popen'
        ./z.lua:278: in function 'os.call'
        ./z.lua:488: in function <./z.lua:470>
        (...tail calls...)
        ./z.lua:2116: in function 'z_shell_init'
        ./z.lua:1833: in function 'main'
        ./z.lua:2553: in main chunk
        [C]: in ?
`
如何make msys32呢

**Comment by skywind3000** [comment]
你 make 的时候忘记加一个宏了，导致编译出来的 lua 没有 io.popen 函数，非标准方式编译的？

**Comment by sherylynn** [comment]
我是按照 [http://lua-users.org/wiki/BuildingLua](url) 和
 [https://www.lua.org/manual/5.3/readme.html](url) 上的建议 直接 `make mingw` 编译的。
具体操作步骤是`pacman -S msys/gcc`后 下载lua5.3.5源码`make mingw`，
这个应该是标准方式编译。用msys的gcc编译的应该是msys版的lua吧，我后来自己写了个lua试了试确实没io.popen函数...

后来我换用`pacman -S mingw-w64-x86_64-toolchain `尝试编译编译mingw版的lua，是有io.popen函数的，但是mingw版的lua在mintty的执行z.lua会提示
`$ eval "$(lua ~/tools/zlua/z.lua --init bash)"`
`stdout is not a tty
`

**Comment by skywind3000** [comment]
我再跟你说一遍，要 msys32 的 lua，不是要 mingw 的 lua

**Comment by sherylynn** [comment]
现在明白了.之前一直想着gcc应该不用mingw版本的gcc
现在在msys里执行`make posix`编译出来的lua就可以用了
非常感谢韦易笑大大，是我自己自己对mingw/msys的无知浪费了您的时间，再次感谢您的耐心
PS:z.lua 真滴好用，因为之前安装不成没办法试用了下基于go跨平台的jump，比z.lua弱智好多啊感觉...

**Comment by wzlayer** [comment]
看了这个 issue 的解决方案后，一开始还是不太明白怎么操作，我猜还有跟我一样的。

git bash 安装 z.lua 步骤：

- 下载 @sherylynn 提供的 lua.zip 到本地并解压，等会儿会用到里面的 lua.exe 文件
- 下载 https://github.com/skywind3000/z.lua 工程里面的 z.lua 文件到本地
- 修改 .bashrc 文件，添加 `eval "$(<your lua.exe path> <your z.lua path> --init bash)”`

> 注意：lua.exe 路径和 z.lua 路径需要使用 git bash 中的文件路径，比如：

`eval "$(/c/Users/DELL/Downloads/lua/lua.exe /c/Users/DELL/Documents/GitHub/z.lua/z.lua --init bash)”`
