### ISSUE TITLE
Command doesn't work correctly for segments with hyphens

### ISSUE THREAD

**Issue by nugend** [skywind3000/z.lua#65]
On 1.7.0

```
[dnugent@local ~/tmp]$ pwd
/home/dnugent/tmp
[dnugent@local ~/tmp]$ mkdir my-dir
[dnugent@local ~/tmp]$ cd my-dir
[dnugent@local ~/tmp/my-dir]$ cd ..
[dnugent@local ~/tmp]$ z my-dir
/home/dnugent/tmp/my-dir
[dnugent@local ~/tmp/my-dir]$ cd ..
[dnugent@local ~/tmp]$ mkdir mydir
[dnugent@local ~/tmp]$ cd mydir
[dnugent@local ~/tmp/mydir]$ cd ..
[dnugent@local ~/tmp]$ z my-dir
/home/dnugent/tmp/mydir
[dnugent@local ~/tmp/mydir]$ cd ..
[dnugent@local ~/tmp]$ z -l my-dir
8          /home/dnugent/tmp/mydir
[dnugent@local ~/tmp]$ kak
[dnugent@local ~/tmp]$ cd my-dir
[dnugent@local ~/tmp/my-dir]$ cd ..
[dnugent@local ~/tmp]$ z -l my
8          /home/dnugent/tmp/mydir
12         /home/dnugent/tmp/my-dir
[dnugent@local ~/tmp]$ z my
/home/dnugent/tmp/my-dir
[dnugent@local ~/tmp/my-dir]$ cd ..
[dnugent@local ~/tmp]$ z my-dir
/home/dnugent/tmp/mydir
[dnugent@local ~/tmp/mydir]$
```

**Comment by skywind3000** [comment]
See the [FAQ](https://github.com/skywind3000/z.lua/wiki/FAQ#how-to-input-a-hyphen---in-the-keyword-)

**Comment by nugend** [comment]
Isn't that only when between left and right square brackets?

**Comment by skywind3000** [comment]
I don't really understand where is the square bracket ?? I think it is explained clearly in the FAQ.

**Comment by nugend** [comment]
Ah, I misread the lua documentation. I thought the dash only appeared in character ranges. Didn't see that it was non-greedy repetition.

Hmm.. would it be unreasonable to have a flag to automatically escape the dashes and then allow `%-` to unescape them?

**Comment by tekumara** [comment]
I migrated from `z.sh` which doesn't have this edge case. So I was expecting `z my-dir` would work. 

+1 for making this work intuitively, ie: without requiring escaping.

**Comment by skywind3000** [comment]
Fair, I added an `$_ZL_HYPHEN` option for this, see here:

https://github.com/skywind3000/z.lua/releases/tag/v1.7.4

**Comment by tekumara** [comment]
Nice, thankyou!

Might be helpful to update the FAQ to mention the new `$_ZL_HYPEN` option too.

**Comment by skywind3000** [comment]
FAQ updated
