### ISSUE TITLE
配置未生效，路径对，安装lua。

### ISSUE THREAD

**Issue by fvstar** [skywind3000/z.lua#75]
想用z.lua 🤕️
![3](https://user-images.githubusercontent.com/22077176/64594474-ac66d200-d3e2-11e9-9eeb-585c967faa91.png)

![2](https://user-images.githubusercontent.com/22077176/64594079-dd92d280-d3e1-11e9-9af3-930294f336c9.png)
然后bash,,zsh中都试着用z跳转，没反应。但是没说“bash:z:未找到命令"之类的话。

**Comment by skywind3000** [comment]
你要先确认你的 bashrc/zshrc 中的那一行生效了，你先别写在 rc 文件中，先在命令行：

```bash
eval "$(lua /home/song/.z.lua/z.lua --init zsh)"
```

执行一下，然后再敲 `z` 命令看看返回值正常不？然后先随便去两个地方：

```bash
cd /etc
cd /home
```

这样数据库里就有记录了，再：

```bash
z etc
```

看看能不能跳转过去。

**Comment by fvstar** [comment]
可以了，👖️ 🙏🏻
之前没用过autojump之类的工具，
才知道“要成功使用，必须要先cd目录，这样子才能生成相应的目录记录，这样子才能使用快捷跳转”

**Comment by skywind3000** [comment]
嗯，某个目录去的次数越多，使用时间约近，会拥有更高的匹配权重，更好的匹配推荐你用：

```bash
eval "$(lua /path/to/z.lua --init zsh enhanced once echo)"
```
