### ISSUE TITLE
fzf not autoinstalled with z.lua.plugin.zsh

### ISSUE THREAD

**Issue by jubishop** [skywind3000/z.lua#77]
i have fzf installed, i'd love it if z.lua.plugin.sh would automatically detect that and add it as part of loading it in my plugin manager, i.e.

zplugin load junegunn/fzf-bin
zplugin light skywind3000/z.lua

**Comment by jubishop** [comment]
actually it appears fzf tab completion only works with bash?

**Comment by skywind3000** [comment]
that's right.

**Comment by kang8** [comment]
Hi, @skywind3000 

I'm unsure why GitHub hasn't closed it yet. Could you please close it? The issue has been resolved.
