### ISSUE TITLE
 delete  directory

### ISSUE THREAD

**Issue by Zeroman** [skywind3000/z.lua#80]
Hi，Can you add a configuration item, don't delete a directory that doesn't exist?

**Comment by skywind3000** [comment]
It is already mentioned in the documentation, try:

    export _ZL_NO_CHECK=1

befor init z.lua

**Comment by Zeroman** [comment]
Thank you very much, I did not read the document carefully.

**Comment by exic** [comment]
To be fair, it's not that clear in the documentation that this option does that :grin:
