### ISSUE TITLE
Does not work with slashes

### ISSUE THREAD

**Issue by kuator** [skywind3000/z.lua#89]
If path contains a slash z.lua does not handle slashes. It works only if slash is escaped:
`z -l my-<tab><tab>` nothing happens
`z -l my\-<tab><tab> -> home/me/directory/my-favourite-directory `

**Comment by skywind3000** [comment]
See here https://github.com/skywind3000/z.lua/issues/65

**Comment by skywind3000** [comment]
Use `$_ZL_HYPHEN`
