### ISSUE TITLE
z.lua does not build ~/.zlua dictionary unless using `--add` flag

### ISSUE THREAD

**Issue by wendtl** [skywind3000/z.lua#97]
Info:
- Mac OSX
- Bash Shell (inside of Byobu)

I've added the following line to my bashrc
`eval "$(lua /Users/logan.wendt/bin/z.lua/z.lua --init bash enhanced)"`

When I attempt to use `z` or `cd` to change directories, none of the directories I try get added to the `~/.zlua` file. The only way that directories get added is if I add them manually using `z --add <directory>`

If I understand correctly, `z.lua` should be building this dictionary automatically as I `cd` around. Am I missing something?

**Comment by skywind3000** [comment]
What is the output of:

    echo $PROMPT_COMMAND

**Comment by wendtl** [comment]
I currently have it set up to display my user, hostname, and pwd:
`echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"`

**Comment by skywind3000** [comment]
obviously, zlua function has been removed by yourself.

Try to init z.lua after your  PROMPT_COMMAND setup.

**Comment by wendtl** [comment]
ah, of course. My mistake. It's working now, thank you!
For anyone who may see this in the future, here is my fixed prompt:
`(_zlua --add "$(command pwd 2>/dev/null)" &);echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"`
